services:
  app:
    image: ghcr.io/lesomnus/cld:${REVISION:-local}
    command: [greet, lesomnus]

    network_mode: host
    privileged: true

    volumes:
      - ./cld.yaml:/cld.yaml:ro

    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 64M
        reservations:
          cpus: "2"
          memory: 32M
